# DEVELOPMENT CONFIGURATION OVERLAY
# USAGE: beet -c dev.yml config -p

#format_item: "[format:$format][bpm:$bpm] ::: $artist - $album - $title"
format_item: "[format:$format][bpm:$bpm] ::: $path"

#bpmanalyser:
#    auto: no
#    dry-run: no
#    write: yes
#    threads: 2
#    force: no
#    quiet: no
