name: Test and Release

on: push

jobs:
  test_and_release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beets
          pip install pytest nose coverage mock six
      - name: Test
        run: |
          pytest
