name: Test and Release

on:
  push
  # branch: master
  # tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test_and_release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beets
          pip install pytest nose coverage mock six
      - name: Test
        run: |
          pytest
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "test release"
          #tag: v1.4.1
          draft: true
          generateReleaseNotes: true
