name: Test and Release

on:
  push:
    tags:
      - "v*"

jobs:
  test_and_release:
    name: Test and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beets
          pip install pytest nose coverage mock six
      - name: Test
        run: |
          pytest
      - name: Create Release
        uses: ncipollo/release-action@v1
        # ref.: https://github.com/ncipollo/release-action
        with:
          name: Test release for ${{ github.ref_name }}
          #tag: ${{ github.ref }}
          draft: true
          generateReleaseNotes: true
