name: Test & Release & Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: ["3.7"]
        python-version: ["3.7", "3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (${{ matrix.python-version }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beets
          pip install pytest nose coverage mock six
      - name: Test
        run: |
          pytest
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: ncipollo/release-action@v1
        # ref.: https://github.com/ncipollo/release-action
        with:
          name: ${{ github.ref_name }}
          draft: false
          generateReleaseNotes: true
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ["release"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          #python setup.py sdist bdist_wheel
          python -m build
          twine check dist/*
          twine upload dist/*
